version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 10
  pre_build:
    commands:
      - npm install
      - npm install -g hexo
  build:
    commands:
      - hexo generate
artifacts:
  files:
    - '**/*'
  base-directory: 'public'
